//! flutter_rust_bridge binding layer for the Askrypt mobile app.
//!
//! All security-critical logic lives in `askrypt-core`; this crate only adapts
//! that API into a session-oriented, FFI-friendly surface for the Flutter UI.
//!
//! Design notes:
//! - Decrypted secrets, answers and the master key never leave Rust. The Dart
//!   side receives only the data it must render ([`api::EntryView`]), and must
//!   ask explicitly to reveal a single secret ([`api::UnlockedVault::reveal_secret`]).
//! - Persisting changes re-creates the vault from the in-memory questions,
//!   answers and entries (mirroring the desktop app) and returns ZIP bytes for
//!   the platform layer to store; this crate performs no filesystem I/O.
//! - Sensitive in-memory state is zeroized when a session is locked/dropped.

pub mod api;

// Generated by `flutter_rust_bridge_codegen` in Phase 2 (needs the Flutter
// project to emit the matching Dart). Until then the crate builds as a plain
// library so the API can be developed and unit-tested standalone.
// mod frb_generated;
